import json
from app.agents.base import BaseAgent
from app.pipeline.state import TradingState


SYSTEM_PROMPT = """You are a quantitative risk manager enforcing strict portfolio constraints
from "151 Trading Strategies" (strategy 3.18 covariance framework):

Constraints:
- Max portfolio drawdown: 15% (circuit breaker)
- Max position size: 5% of equity (Kelly criterion half-Kelly)
- Max sector concentration: 30%
- New position correlation < 0.7 with existing holdings
- Target portfolio volatility: 10% annualized (strategy 6.5)
- Dollar neutrality for stat-arb positions

Respond ONLY with a valid JSON object:
{
  "approved": <bool>,
  "position_size_pct": <float 0-5>,
  "kelly_fraction": <float>,
  "stop_loss_adjustment": <float>,
  "portfolio_drawdown": <float 0-100>,
  "sector_concentration": <float 0-100>,
  "correlation_check": <float -1 to 1>,
  "vol_scalar": <float>,
  "warnings": [<string>, ...],
  "reasoning": "<string>"
}"""


def kelly_criterion(win_prob: float, reward_risk_ratio: float) -> float:
    """Kelly fraction f* = (p*b - q) / b where b = reward/risk, p = P(win), q = 1-p"""
    q = 1 - win_prob
    b = reward_risk_ratio
    if b <= 0:
        return 0.0
    return max(0, (win_prob * b - q) / b)


class RiskManager(BaseAgent):
    def __init__(self):
        super().__init__("RiskManager", tier="standard")

    async def analyze(self, state: TradingState) -> dict:
        ticker = state.get("ticker", "UNKNOWN")
        tech = state.get("technical_analysis", {})
        fund = state.get("fundamental_analysis", {})

        # Aggregate confidence from the analysts that actually saw data.
        # An agent that abstained returns confidence 0, and averaging that in
        # would read "no data" as "certain there is no edge" - two very
        # different inputs. Abstentions are excluded, not counted as zero and
        # not defaulted to a neutral 50 either, which is what the old
        # `.get("confidence", 50)` did for every missing agent.
        analyses = [
            state.get("fundamental_analysis", {}),
            state.get("technical_analysis", {}),
            state.get("sentiment_analysis", {}),
            state.get("macro_analysis", {}),
        ]
        scored = [a.get("confidence", 0) for a in analyses if a and not a.get("abstained")]
        avg_confidence = (sum(scored) / len(scored)) if scored else 0.0

        # Kelly needs a WIN RATE. This used to pass `avg_confidence / 100`,
        # which is not one: "the analysts are 65% confident" and "65% of these
        # trades win" are different quantities, and Kelly is violently
        # sensitive to the difference - overstating p by 10 points can more
        # than double the recommended size. The only real win rate available
        # came from the quant agent, and that number was generated by
        # rng.uniform until today. So there is currently no measured win rate
        # to size from, and Kelly is not computed rather than being computed
        # from a stand-in.
        measured_wr = state.get("quant_validation", {}).get("backtest_win_rate")

        # Levels must come from the technical agent. The old defaults - entry
        # 100, stop 95, target 110 - produced a reward/risk figure for a
        # symbol trading at 4,400 or 181 whenever support was missing.
        support = tech.get("support") if tech else None
        resistance = tech.get("resistance") if tech else None
        if support and resistance and resistance > support:
            entry = support * 1.01
            stop = support
            reward_risk = (resistance - entry) / max(entry - stop, 1e-9)
        else:
            entry = stop = reward_risk = None

        if measured_wr is not None and reward_risk:
            kelly = kelly_criterion(measured_wr, reward_risk)
            half_kelly = kelly / 2
            position_size = round(min(5.0, half_kelly * 100), 2)
        else:
            kelly = half_kelly = None
            position_size = None

        portfolio = state.get("portfolio_stats", {})
        port_drawdown = portfolio.get("drawdown_pct", 0.0)
        port_sector_exposure = portfolio.get("sector_exposure_pct", 0.0)
        port_correlation = portfolio.get("avg_correlation", 0.0)

        strategy_ctx = self._strategy_context(state)
        # Every interpolation is guarded: kelly, reward_risk and position_size
        # are None whenever there is no measured win rate or no technical
        # levels, and "{kelly:.3f}" on None raises.
        _kelly_txt = f"{kelly:.3f}" if kelly is not None else "not computed (no measured win rate)"
        _size_txt = f"{position_size:.1f}%" if position_size is not None else "not computed"
        _rr_txt = f"{reward_risk:.2f}" if reward_risk is not None else "unavailable (no technical levels)"
        user_msg = f"""{strategy_ctx}Validate risk for {ticker}.
Analyst confidence (abstentions excluded): {avg_confidence:.1f}% from {len(scored)} analysts
Kelly fraction: {_kelly_txt} → Half-Kelly position size: {_size_txt}
Estimated reward/risk ratio: {_rr_txt}
Portfolio drawdown: {port_drawdown:.1f}%
Sector exposure: {port_sector_exposure:.1f}%
Correlation with existing positions: {port_correlation:.2f}

Apply all risk constraints. Output JSON only."""

        raw = await self._call_claude(SYSTEM_PROMPT, user_msg, state=state)
        if raw:
            try:
                result = json.loads(raw)
                if kelly is not None:
                    result.setdefault("kelly_fraction", round(kelly, 4))
                result.setdefault("position_size_pct", position_size)
                return result
            except json.JSONDecodeError:
                pass

        return self._mock_analysis(ticker, kelly, half_kelly, position_size, avg_confidence, reward_risk, portfolio)

    def _mock_analysis(self, ticker, kelly, half_kelly, position_size, avg_confidence,
                       reward_risk, portfolio: dict | None = None) -> dict:
        """Risk check from the real portfolio, or an explicit refusal to size.

        This method used to invent the entire portfolio it was protecting:

            drawdown    = rng.uniform(1, 12)
            sector_conc = rng.uniform(5, 28)
            correlation = rng.uniform(0.1, 0.65)
            vol_scalar  = rng.uniform(0.7, 1.2)

        then compared those numbers against the 15% / 30% / 0.70 limits and
        announced APPROVED or REJECTED. A risk manager that makes up the
        exposure it is checking is not a control, and it approved or blocked
        real signals on the strength of it.

        Portfolio figures now come from state["portfolio_stats"], which is
        real when a portfolio exists and zero when none does - and zero
        exposure genuinely cannot breach a concentration limit, so that is a
        sound reading rather than an optimistic one.
        """
        portfolio = portfolio or {}
        drawdown = portfolio.get("drawdown_pct", 0.0)
        sector_conc = portfolio.get("sector_exposure_pct", 0.0)
        correlation = portfolio.get("avg_correlation", 0.0)
        has_portfolio = bool(portfolio)

        warnings = []
        if drawdown > 10:
            warnings.append(f"Portfolio drawdown at {drawdown:.1f}%, approaching 15% limit")
        if sector_conc > 25:
            warnings.append(f"Sector concentration at {sector_conc:.1f}%, near 30% cap")
        if not has_portfolio:
            warnings.append("No portfolio data - concentration and correlation limits could not be checked")
        if position_size is None:
            warnings.append(
                "Position size NOT calculated: Kelly needs a measured win rate and this "
                "setup has no backtest behind it. Size this manually."
            )
        elif position_size < 0.5:
            warnings.append("Low Kelly fraction suggests weak edge - consider passing")

        # Approval no longer depends on confidence standing in for a win rate.
        # It reports whether the checkable limits are breached; a signal with
        # no measurable edge is not "rejected" here, it is unsized, and the
        # trader decides what to do about that.
        approved = drawdown < 15 and sector_conc < 30 and correlation < 0.7

        _kelly_txt = f"{kelly:.3f}" if kelly is not None else "not computed"
        _size_txt = f"{position_size:.1f}%" if position_size is not None else "not computed"
        return {
            "approved": approved,
            "position_size_pct": position_size,
            "kelly_fraction": round(kelly, 4) if kelly is not None else None,
            "stop_loss_adjustment": 0.0,
            "portfolio_drawdown": round(drawdown, 2),
            "sector_concentration": round(sector_conc, 1),
            "correlation_check": round(correlation, 3),
            "vol_scalar": 1.0,
            "warnings": warnings,
            "reasoning": (
                f"Risk check for {ticker}: Kelly={_kelly_txt}, position size {_size_txt}. "
                + (f"Portfolio drawdown {drawdown:.1f}% (limit 15%), "
                   f"sector concentration {sector_conc:.1f}% (limit 30%), "
                   f"correlation {correlation:.2f} (limit 0.70). "
                   if has_portfolio else "No open portfolio to check limits against. ")
                + f"Checkable limits {'PASS' if approved else 'BREACHED'}."
            ),
        }
